services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mon_broker_mqtt
    ports:
      - "1884:1883"  # MQTT -> hôte:1884
      - "9002:9001"  # WebSockets -> hôte:9002
    volumes:
      - ./mosquitto_config:/mosquitto/config:rw
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: mon_serveur_nginx
    ports:
      - "8080:80"   # HTTP -> hôte:8080
      - "4443:443"  # HTTPS -> hôte:4443
    volumes:
      - ./nginx_html:/usr/share/nginx/html  # Fichiers statiques

  influxdb:
      image: influxdb:2
      container_name: influxdb
      ports:
        - "8086:8086"  # Port par défaut d'InfluxDB
      volumes:
        - influxdb_data:/var/lib/influxdb  # Persistance des données
      environment:
        INFLUXDB_DB: my_database  # Crée une base de données par défaut
        INFLUXDB_ADMIN_USER: admin  # Utilisateur admin
        INFLUXDB_ADMIN_PASSWORD: admin_password  # Mot de passe admin
  
  grafana:
      image: grafana/grafana
      container_name: grafana
      restart: unless-stopped
      ports:
      - '3000:3000'
      volumes:
        - grafana-storage:/var/lib/grafana
    

volumes:
  influxdb_data:
  grafana-storage: {}
