services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mon_broker_mqtt
    ports:
      - "1884:1883"  # MQTT -> hôte:1884
      - "9002:9001"  # WebSockets -> hôte:9002
    volumes:
      - ./mosquitto_config:/mosquitto/config:rw
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: mon_serveur_nginx
    ports:
      - "8080:80"   # HTTP -> hôte:8080
      - "4443:443"  # HTTPS -> hôte:4443
    volumes:
      - ./nginx_html:/usr/share/nginx/html  # Fichiers statiques

  influxdb:
    image: influxdb:2.1.1
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086
  
  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - ./grafana-dashboard:/var/lib/grafana:rw  # Monter le dossier local
    depends_on:
      - influxdb
    ports:
      - "3000:3000"  # Assure-toi que le port est bien défini
    

volumes:
  grafana-storage:
  influxdb-storage: